AllCops:
  TargetRubyVersion: 3.3.0
  SuggestExtensions: false
  NewCops: enable

Lint/ConstantDefinitionInBlock:
  Exclude:
    - test/**/*

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - fixtures/**/*

Metrics/BlockLength:
  Exclude:
    - test/**/*
Metrics/MethodLength:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 8
