AllCops:
  TargetRubyVersion: 3.3.0
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - gemfiles/**/*

Lint/ConstantDefinitionInBlock:
  Exclude:
    - test/**/*

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - fixtures/**/*

Metrics:
  Enabled: false
