name: main

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        ruby:
          - "3.3.0"
          - "3.4.0"
    runs-on: ${{ matrix.os }}

    env:
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec appraisal install
      - run: bundle exec appraisal sus

  rubocop:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop -P --fail-level C
